### ISSUE TITLE
Temporary files are never cleaned

### ISSUE THREAD

**Issue by ctgraham** [VTUL/EzidDOI#19]
Calls to cleanTmpfiles() are present in processRegisterObjects() and in registerObjects().

The $exportFiles array in registerObjects() is spurrious; it can never be populated.
https://github.com/VTUL/EzidDOI/blob/3c4fb7c69d2a4cf6448262bef9756eb54048a8b3/EzidRegisterPlugin.inc.php#L236

The $exportFiles array in processRegistereObjects() should be populated by the $exportFileName assignments.
https://github.com/VTUL/EzidDOI/blob/3c4fb7c69d2a4cf6448262bef9756eb54048a8b3/EzidRegisterPlugin.inc.php#L267
Because an empty array is passed to cleanTmpfiles(), no temp files are ever removed.

**Comment by logpanic** [comment]
fixed by PR #20
