### ISSUE TITLE
500 Server error when registering

### ISSUE THREAD

**Issue by logpanic** [VTUL/EzidDOI#28]
Looking back through the issues, PRs, and comments I can see that I ran into this issue before: https://github.com/VTUL/EzidDOI/pull/14#issuecomment-145918751

I'm not sure how I remedied it though; however, I'm getting a 500 internal server error when I try registering an article or issue both on my local instance and our development instance. @ctgraham, can you replicate this?

All I did from when last setup when the plugin worked:

Deleted old plugin, installed new plugin via web interface.

**Comment by ctgraham** [comment]
Is this a 500 error from OJS, or from EZID?  The EZID errors usually have some useful messaging passed through as the [`$response`](https://github.com/VTUL/EzidDOI/blob/master/EzidRegisterPlugin.inc.php#L285).

Can you get any more details?

**Comment by logpanic** [comment]
My mistake :flushed:, curl wasn't installed on the local.
