### ISSUE TITLE
Changing the article DOI breaks the plugin links

### ISSUE THREAD

**Issue by ctgraham** [VTUL/EzidDOI#4]
Steps to reproduce:
- Register DOIs via the plugin
- Reset one or more DOIs via Journal Setup or Editor functions
- Return to the EZID "Select Articles" list

Expected result: The "EDIT" and "STATUS" links reflect the previously registered DOI for the article.
Actual result: The "EDIT" and "STATUS" links use the newly reset (or missing) DOI.

**Comment by logpanic** [comment]
Looks good!
