### ISSUE TITLE
Register Issue function fails

### ISSUE THREAD

**Issue by ctgraham** [VTUL/EzidDOI#6]
Steps to reproduce:
- Import/Export Data ->
- EZID Export/Registration Plugin ->
- All Issues ->
- (Select Issue with more than one article) Register

Expected result: _Uncertain._  Issue DOI is registered?  Individual Article DOIs are registered serially?  Both?
Actual result: "Registration was not successful! The DOI registration server returned an error: '400 - error: bad request - element 'crossref': malformed CrossRef submission metadata'."

I think this is related to [EZID's requirement](http://ezid.cdlib.org/doc/apidoc.html#crossref-registration) that a CrossRef submission have only one `<doi_data>` element.

**Comment by logpanic** [comment]
Ah, I see. We should probably have it check the PubID DOI settings and have it parse out according;
for example, if the `Issues` and `Articles` boxes are checked, register the DOI for the Issue and register the individual article DOIs, serially. And if only one is checked, have it handle that one. 

Thoughts?

**Comment by ctgraham** [comment]
That makes sense to me.

**Comment by ctgraham** [comment]
It looks like EzidRegisterPlugin retains CrossRefExportPlugin's assumption that only articles DOIs are to be registered.:
https://github.com/VTUL/EzidDOI/blob/378fed0199883a5596e3c27282e4d68f3865e5fe/EzidRegisterPlugin.inc.php#L104
https://github.com/VTUL/EzidDOI/blob/378fed0199883a5596e3c27282e4d68f3865e5fe/EzidRegisterPlugin.inc.php#L165

Is this a legitimate assumption for EZID?  Is this a required assumption if registering an EZID DOI with a Crossref schema?

**Comment by logpanic** [comment]
PR #14 solved issue #3 with regard to article xml export and article registration. However, the issue XML still needs a doi_node with the doi information.

**Comment by ctgraham** [comment]
I'm trying to replicate this issue, @chasehd .  When using the DOI plugin settings (selecting Issues and Articles, applying "10.5072" as the DOI prefix, and "FK2%j.v%vi%i" for issues and "FK2%j.v%vi%i.%a" for articles), my test does have a `<doi_data>` element containing a `<doi>` element when exporting or registering an issue.  Using the shoulder in the EZID plugin instead of the DOI plugin settings still presents the `<doi_data>` element and `<doi>` element, though it doesn't respect the mint vs. put distinction intended.  I'll look into that further.  Can you share your settings so I can try to reproduce the missing node as well?

**Comment by ctgraham** [comment]
~~Actually, if you are depending on the minting function, that might be the issue right there.  I'll look into that further tomorrow.~~

**Comment by ctgraham** [comment]
Striking my former comment.  The minting new vs registering existing was a data issue on my end.

I've tested the Issue registration successfully in my test journal, with the settings described above.

Can you elaborate on the issue you're experiencing?

**Comment by logpanic** [comment]
Whether the shoulder is present or not, when I export an issue, no articles are present in the XML and there is no doi node. See: https://gist.github.com/chasehd/27e50f80d99403cc2960

**Comment by ctgraham** [comment]
Do you have the DOI Plugin configured to create Issue DOIs?  I think this will be required for the Crossref plugin, and thus the EZID plugin, to output Issue DOIs.  I also think configuration of the DOI Plugin as such should be required.

I also think the exclusion of article nodes in the issue XML is desired behavior.

The articles are registered separately in individual API requests prior to the issue registration.
https://github.com/VTUL/EzidDOI/blob/master/EzidRegisterPlugin.inc.php#L192

The `doi_data` element is mandatory for the `journal_article` element, at least in [Crossref 4.3.3](http://doi.crossref.org/schemas/crossref4.3.3.xsd), so including the articles without DOIs in the issue export would be malformed.

Thoughts?

**Comment by logpanic** [comment]
Closing issue. The journal issue I was working with didn't have a published date, which is why the doi node wasn't generated.
